version: '3.8'

services:
  onelastai-web:
    build: .
    container_name: onelastai-platform
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future backend services can be added here
  # onelastai-api:
  #   image: onelastai/api:latest
  #   container_name: onelastai-api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=${DATABASE_URL}
  #   restart: unless-stopped

networks:
  default:
    name: onelastai-network
